project:
  type: website

website:
  title: "Sorina & Thomas' Wedding"
  navbar:
    left:
      - href: index.qmd
        text: Invitation
      - href: about.qmd
        text: What To Expect
      - href: rsvp.qmd
        text: RSVP
      - href: messages.qmd
        text: Messages
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

